# Generated by Django 2.1.2 on 2018-10-30 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=63)),
                ('topic', models.CharField(choices=[('A', 'General'), ('B', 'Social'), ('C', 'Professional'), ('D', 'Philanthropy'), ('E', 'Recruitment'), ('F', 'New Member')], default='A', max_length=1)),
                ('type', models.CharField(choices=[('G', 'Normal'), ('H', 'Urgent')], default='G', max_length=1)),
                ('message', models.TextField()),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.Profile')),
            ],
        ),
    ]
