# Generated by Django 2.1.2 on 2018-11-28 22:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=63)),
                ('topic', models.CharField(choices=[('A', 'General'), ('B', 'Social'), ('C', 'Professional'), ('D', 'Philanthropy'), ('E', 'Recruitment'), ('F', 'New Member'), ('G', 'Brotherhood Development')], default='A', max_length=1)),
                ('is_public', models.BooleanField(default=False)),
                ('description', models.TextField()),
                ('address', models.CharField(max_length=127)),
                ('city', models.CharField(max_length=31)),
                ('state', models.CharField(max_length=15)),
                ('zipcode', models.CharField(max_length=5)),
                ('dateAdded', models.DateTimeField(auto_now_add=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
