# Generated by Django 2.1.2 on 2018-10-29 15:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import member.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cell_Carriers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63)),
                ('sms_address', models.CharField(max_length=63, verbose_name='SMS Email Gateway')),
            ],
        ),
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=63)),
            ],
        ),
        migrations.CreateModel(
            name='Job_History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=63)),
                ('state', models.CharField(max_length=31)),
                ('city', models.CharField(max_length=31)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.Companies')),
            ],
        ),
        migrations.CreateModel(
            name='Organization_Involvement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=63)),
            ],
        ),
        migrations.CreateModel(
            name='Organizations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=63)),
                ('type', models.CharField(choices=[('A', 'Appointed'), ('B', 'Elected'), ('C', 'Executive Board')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Position_History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(choices=[('S', 'Spring'), ('F', 'Fall')], max_length=1)),
                ('year', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('phone', models.CharField(blank=True, max_length=14, verbose_name='phone number')),
                ('address', models.CharField(blank=True, max_length=255)),
                ('pledge_class', models.CharField(blank=True, max_length=31)),
                ('major', models.CharField(blank=True, max_length=63, verbose_name='decalared major')),
                ('major2', models.CharField(blank=True, max_length=63, verbose_name='second major')),
                ('emphasis', models.CharField(blank=True, max_length=63)),
                ('grad_semester', models.CharField(blank=True, choices=[('S', 'Spring'), ('F', 'Fall')], max_length=1, verbose_name='semester graduating')),
                ('grad_year', models.CharField(blank=True, max_length=4, verbose_name='year graduating')),
                ('shirt_size', models.CharField(blank=True, choices=[('M', 'Medium'), ('XS', 'Extra Small'), ('S', 'Small'), ('L', 'Large'), ('XL', 'Extra Large'), ('XXL', 'Double XL'), ('XXXL', 'Triple XL')], max_length=4)),
                ('member_status', models.CharField(blank=True, choices=[('A', 'Active'), ('B', 'Alumni'), ('C', 'Inactive'), ('D', 'New Member')], max_length=1)),
                ('linkedin_profile', models.URLField(blank=True, max_length=255)),
                ('cumulative_gpa', models.FloatField(blank=True, null=True, verbose_name='cumulative GPA')),
                ('last_sem_gpa', models.FloatField(blank=True, null=True, verbose_name='last semester GPA')),
                ('last_update', models.DateField(blank=True, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, upload_to=member.models.gen_file_path)),
                ('last_random_pic_date', models.DateField(blank=True, null=True)),
                ('cell_carrier_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='member.Cell_Carriers')),
                ('jobs', models.ManyToManyField(through='member.Job_History', to='member.Companies')),
                ('organizations', models.ManyToManyField(through='member.Organization_Involvement', to='member.Organizations')),
                ('pledge_father', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='member.Profile')),
                ('positions', models.ManyToManyField(through='member.Position_History', to='member.Position')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='position_history',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.Profile'),
        ),
        migrations.AddField(
            model_name='position_history',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.Position'),
        ),
        migrations.AddField(
            model_name='organization_involvement',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.Organizations'),
        ),
        migrations.AddField(
            model_name='organization_involvement',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.Profile'),
        ),
        migrations.AddField(
            model_name='job_history',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.Profile'),
        ),
    ]
